name: NEI CI - Production Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      ALLOWED_HOST: ${{ secrets.ALLOWED_HOST }}
      GRAFANA_USER: ${{ secrets.GRAFANA_USER }}
      GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.prod.yml
          down-flags: "--remove-orphans --volumes"
          
      - name: Run Django Tests
        run: docker compose exec -T django python manage.py test
